# Generated by Django 6.0.3 on 2026-03-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Фамилия"
            ),
        ),
    ]
