# Generated by Django 6.0.3 on 2026-03-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name="Токен"),
        ),
    ]
