# Generated by Django 6.0.3 on 2026-03-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TextContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_content", models.CharField(max_length=20)),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "Текстовый контент",
                "verbose_name_plural": "Текстовые контенты",
            },
        ),
    ]
