# Generated by Django 6.0.3 on 2026-03-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentForSite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name_content", models.CharField(max_length=20)),
                ("text", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="media/image_for_site/")),
            ],
            options={
                "verbose_name": "Контент для сайта",
                "verbose_name_plural": "Контенты для сайта",
            },
        ),
        migrations.DeleteModel(
            name="TextContent",
        ),
    ]
