# Generated by Django 6.0.3 on 2026-03-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contentforsite_delete_textcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentforsite",
            name="name_content",
            field=models.CharField(max_length=30),
        ),
    ]
