# Generated by Django 6.0.3 on 2026-03-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_contentforsite_name_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentforsite",
            options={"verbose_name": "Контент для сайта", "verbose_name_plural": "Блоки контента для вставки"},
        ),
        migrations.AddField(
            model_name="contentforsite",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
