# Generated by Django 6.0.3 on 2026-03-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_contentforsite_options_contentforsite_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentforsite",
            options={"verbose_name": "Блок контента для сайта", "verbose_name_plural": "Блоки контента для вставки"},
        ),
        migrations.RenameField(
            model_name='contentforsite',
            old_name='name_content',
            new_name='name_tag',
        ),

    ]
