# Generated by Django 6.0.3 on 2026-03-13 03:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_table",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[django.core.validators.MaxValueValidator(6)],
                        verbose_name="Номер столика",
                    ),
                ),
                (
                    "num_of_seats",
                    models.PositiveIntegerField(
                        verbose_name="Максимальное количество посадочных мест"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=400, verbose_name="Описание столика"),
                ),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_visit", models.DateField(verbose_name="Дата визита")),
                ("time_visit", models.TimeField(verbose_name="Время визита")),
                (
                    "duration_visit",
                    models.PositiveIntegerField(
                        default=120, verbose_name="Длительность (в минутах)"
                    ),
                ),
                (
                    "deposit",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(50000)],
                        verbose_name="Сумма депозита",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь совершивший бронирование",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table_reservation.table",
                        verbose_name="Номер столика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
    ]
