# Generated by Django 6.0.3 on 2026-03-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("table_reservation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="client",
            new_name="owner",
        ),
    ]
