# Generated by Django 6.0.3 on 2026-03-17 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0002_rename_client_reservation_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_visit',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='duration_visit',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time_visit',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 17, 23, 16, 31, 403422), verbose_name='Конец бронирования'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 17, 23, 16, 39, 276506), verbose_name='Начало бронирования'),
            preserve_default=False,
        ),
    ]
