# Generated by Django 6.0.3 on 2026-03-22 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("table_reservation", "0003_remove_reservation_date_visit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="min_deposit",
            field=models.PositiveIntegerField(
                default=2000,
                validators=[django.core.validators.MaxValueValidator(50000)],
                verbose_name="Минимальная сумма депозита",
            ),
            preserve_default=False,
        ),
    ]
